import { useState, useEffect } from 'react';
import { Settings } from '../types';
import { DEFAULT_SETTINGS } from '../constants/settings';
import { API_ENDPOINTS } from '../constants/api';

export function useSettings() {
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS);

  useEffect(() => {
    // Load initial settings
    fetch(API_ENDPOINTS.SETTINGS)
      .then(res => res.json())
      .then(data => {
        // Use ?? (nullish coalescing) so that falsy-but-valid values
        // like 0 (number) or false (boolean) from settings.json are
        // preserved. Using || would silently replace them with UI defaults.
        setSettings({
          CLAUDE_MEM_MODEL: data.CLAUDE_MEM_MODEL ?? DEFAULT_SETTINGS.CLAUDE_MEM_MODEL,
          CLAUDE_MEM_CONTEXT_OBSERVATIONS: data.CLAUDE_MEM_CONTEXT_OBSERVATIONS ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_OBSERVATIONS,
          CLAUDE_MEM_WORKER_PORT: data.CLAUDE_MEM_WORKER_PORT ?? DEFAULT_SETTINGS.CLAUDE_MEM_WORKER_PORT,
          CLAUDE_MEM_WORKER_HOST: data.CLAUDE_MEM_WORKER_HOST ?? DEFAULT_SETTINGS.CLAUDE_MEM_WORKER_HOST,

          // AI Provider Configuration
          CLAUDE_MEM_PROVIDER: data.CLAUDE_MEM_PROVIDER ?? DEFAULT_SETTINGS.CLAUDE_MEM_PROVIDER,
          CLAUDE_MEM_OPENAI_API_KEY: data.CLAUDE_MEM_OPENAI_API_KEY ?? DEFAULT_SETTINGS.CLAUDE_MEM_OPENAI_API_KEY,
          CLAUDE_MEM_OPENAI_MODEL: data.CLAUDE_MEM_OPENAI_MODEL ?? DEFAULT_SETTINGS.CLAUDE_MEM_OPENAI_MODEL,
          CLAUDE_MEM_OPENAI_BASE_URL: data.CLAUDE_MEM_OPENAI_BASE_URL ?? DEFAULT_SETTINGS.CLAUDE_MEM_OPENAI_BASE_URL,
          CLAUDE_MEM_BYPASS_COOLDOWN_MS: data.CLAUDE_MEM_BYPASS_COOLDOWN_MS ?? DEFAULT_SETTINGS.CLAUDE_MEM_BYPASS_COOLDOWN_MS,
          CLAUDE_MEM_BYPASS_QUOTA_COOLDOWN_MS: data.CLAUDE_MEM_BYPASS_QUOTA_COOLDOWN_MS ?? DEFAULT_SETTINGS.CLAUDE_MEM_BYPASS_QUOTA_COOLDOWN_MS,
          CLAUDE_MEM_BYPASS_AUTH_COOLDOWN_MS: data.CLAUDE_MEM_BYPASS_AUTH_COOLDOWN_MS ?? DEFAULT_SETTINGS.CLAUDE_MEM_BYPASS_AUTH_COOLDOWN_MS,
          CLAUDE_MEM_BYPASS_MAX_FAILURES: data.CLAUDE_MEM_BYPASS_MAX_FAILURES ?? DEFAULT_SETTINGS.CLAUDE_MEM_BYPASS_MAX_FAILURES,
          CLAUDE_MEM_BYPASS_CONCURRENCY: data.CLAUDE_MEM_BYPASS_CONCURRENCY ?? DEFAULT_SETTINGS.CLAUDE_MEM_BYPASS_CONCURRENCY,
          CLAUDE_MEM_BYPASS_MAX_CONSUMERS: data.CLAUDE_MEM_BYPASS_MAX_CONSUMERS ?? DEFAULT_SETTINGS.CLAUDE_MEM_BYPASS_MAX_CONSUMERS,

          // Token Economics Display
          CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS: data.CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS,
          CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS: data.CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS,
          CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: data.CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT,
          CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: data.CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT,

          // Display Configuration
          CLAUDE_MEM_CONTEXT_FULL_COUNT: data.CLAUDE_MEM_CONTEXT_FULL_COUNT ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_FULL_COUNT,
          CLAUDE_MEM_CONTEXT_FULL_FIELD: data.CLAUDE_MEM_CONTEXT_FULL_FIELD ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_FULL_FIELD,
          CLAUDE_MEM_CONTEXT_SESSION_COUNT: data.CLAUDE_MEM_CONTEXT_SESSION_COUNT ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SESSION_COUNT,

          // Feature Toggles
          CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY: data.CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY,
          CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE: data.CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE,
        });
      })
      .catch(error => {
        console.error('Failed to load settings:', error);
      });
  }, []);

  const saveSettings = async (newSettings: Settings) => {
    const response = await fetch(API_ENDPOINTS.SETTINGS, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newSettings)
    });

    const result = await response.json();
    if (!response.ok || !result.success) {
      throw new Error(result.error || 'Failed to save settings');
    }
    setSettings(newSettings);
  };

  return { settings, saveSettings };
}
